steps:

  # =========================
  # 🔧 BUILD ANGULAR
  # =========================
  - name: 'node:20'
    dir: 'frontend'
    entrypoint: bash
    env: 
      - 'NODE_OPTIONS=--openssl-legacy-provider'
    args:
      - -c
      - |
        echo "📦 Instalando dependências..."
        npm install

        echo "🏗 Buildando Angular..."
        npm install -g @angular/cli
        ng build
        echo "📂 Estrutura completa:"
        ls -R

  # =========================
  # ☁️ DEPLOY PARA BUCKET
  # =========================
  #- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #  entrypoint: bash
  #  args:
  #    - -c
  #    - |
  #      echo "☁️ Enviando arquivos para o bucket..."
  #      gsutil -m rsync -r workspace/dist/frontend gs://exemplo-frontend

options:
  logging: CLOUD_LOGGING_ONLY