steps:

  # =========================
  # 🔧 BUILD ANGULAR
  # =========================
  - name: 'node:20'
    dir: 'frontend'
    entrypoint: bash
    env: 
      - 'NODE_OPTIONS=--openssl-legacy-provider'
    args:
      - -c
      - |
        echo "📦 Instalando dependências..."
        npm install

        echo "🏗 Buildando Angular..."
        npm install -g @angular/cli
        ng build --base-href ./

        echo "📂 Onde estou:"
        pwd

        echo "📂 Listando tudo na raiz do workspace:"
        ls -la /workspace

        echo "📂 Conteúdo do dist:"
        ls -R /workspace/dist

  # =========================
  # ☁️ DEPLOY PARA BUCKET
  # =========================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        echo "☁️ Enviando arquivos para o bucket..."
        gsutil -m rsync -r /workspace/dist/frontend/browser gs://exemplo-frontend

options:
  logging: CLOUD_LOGGING_ONLY